### ISSUE TITLE
1.0.0 관련 이슈

### ISSUE THREAD

**Issue by zozero94** [ZeroFriends/GoStopCalculator#18]
- [x] 앱 스토어 정상 배포 확인
- [x] 라운드 하단 패딩값 조절
- [x] 광고 에러시에도 화면 넘어가도록 수정
- [x] 앱설명에 화투 단어 넣기
- [x] 광고 속도 개선
- [x] 네트워크 연결상태가 아니라면 광고 못보게 막기

**Comment by asas569266** [comment]
앱설명에 화투 단어 넣기
광고 후 로딩

**Comment by zozero94** [comment]
마크다운 공부하자 @asas569266
